on:
  push:
  pull_request:

name: "Test"
jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y fio ioping shellcheck

      - name: CPU probe
        run: |
          set -x
          lscpu
          free -h
          mount

      - name: Shellcheck
        run: |
          shellcheck iotest.sh

      # - name: Run
      #   run: |
      #     time ./iotest.sh
